### ISSUE TITLE
Modal upgrade

### ISSUE THREAD

**Issue by ronencamera** [Dogfalo/materialize#4120]
when upgrading to 0.97.8 from 0.97.7 modal stops working. and i am receiving an error. 

I am calling the 

Uncaught TypeError: $(...).openModal is not a function

**Comment by Dogfalo** [comment]
The modal API was changed to be more consistent with the other plugins
`$('#modal1').modal('open');`

**Comment by ronencamera** [comment]
Well there are more breaking changes my friend. I am using it with angular.io
