### ISSUE TITLE
jQuery.easing[jQuery.easing.def] is not a function

### ISSUE THREAD

**Issue by ktmn** [Dogfalo/materialize#1466]
When I do 

    $(".dropdown-button").dropdown();

the dropdown opens fine, but when I click somewhere else and it's time for the dropdown to close it says

    jQuery.easing[jQuery.easing.def] is not a function

I'm using these versions:

    https://code.jquery.com/jquery-2.1.1.min.js
    https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js

**Comment by ktmn** [comment]
I described a workaround in #1472

**Comment by derekdowling** [comment]
I'm seeing this same issue but with: `$("select").material_select();`

**Comment by tomicakorac** [comment]
@derekdowling same problem here, Materialize `0.97.1`. Were you able to fix it?

@ktmn can you please explain your workaround? I don't think I understand it, sorry.

**Comment by ktmn** [comment]
@tomicakorac Install hammerjs and pickadate with npm, import with webpack or similar.

**Comment by derekdowling** [comment]
For now I reverted to using `browser-default` which seems to work fine but isn't quite as nice looking. Also on 0.97.1

**Comment by derekdowling** [comment]
Still not working as of 0.97.5. Attempted to do as @tomicakorac outlined, didn't seem to solve it for me.

**Comment by m-gv** [comment]
Still experiencing issues with this on v0.97.5 as well. Any options?

**Comment by m-gv** [comment]
It turned out one of the dependencies in my project was using 2.1.3. This version of JQuery no longer seems to set JQuery.easing.def to easeOutQuad by default, thus there will be an undefined error. 

I solved this by forcing materialize to use JQuery 2.1.1 in the following way:
``

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript"> 
     $materialize = jQuery.noConflict(true); 
</script> 

Inside materialize.js:
``
if (typeof(jQuery) === 'undefined') {
  var jQuery;
  // Check if require is a defined function.
  if (typeof(require) === 'function') {
    jQuery = $materialize = require('jQuery');
  // Else use the dollar sign alias.
  } else {
    jQuery = $materialize;
  }
};
``
However now it is no longer possible to use the CDN version and to update without making changes to the materialize file. People working on the project after me will likely run into issues with the way I am currently solving it.

It would be great to get an official statement from @Dogfalo on how you should use materialize while you you have external modules which are using other versions of JQuery. (I don't have access to those extrernal modules)

**Comment by Kail0** [comment]
Above solution from @m-gv works great..

**Comment by zmarket** [comment]
@m-gv  works for me too 👍

**Comment by csalexwilliams** [comment]
@m-gv Great solution. Thanks!

**Comment by Aewil** [comment]
Hello guys,

I've the same issue but i don't have the easing plugin, do you know how to solve it ?

Thank you ;)

**Comment by Vidhyazdo** [comment]
I got this error how to fix it


Uncaught TypeError: jQuery.easing[jQuery.easing.def] is not a function
    at Object.swing (materialize.js:62)
    at init.run (jquery-2.1.1.min.js:3)
    at i (jquery-2.1.1.min.js:3)
    at Function.n.fx.timer (jquery-2.1.1.min.js:3)
    at Xb (jquery-2.1.1.min.js:3)
    at HTMLUListElement.g (jquery-2.1.1.min.js:3)
    at Function.dequeue (jquery-2.1.1.min.js:3)
    at HTMLUListElement.<anonymous> (jquery-2.1.1.min.js:3)
    at Function.each (jquery-2.1.1.min.js:2)
    at n.fn.init.each (jquery-2.1.1.min.js:2

**Comment by kmmbvnr** [comment]
I've got the same error when upgrading to 0.99, b/c in my custom build of Materialize, I didn't update jquery.easing version

https://github.com/Dogfalo/materialize/blob/e6576cc6308efd301d2de57279173bb89332f5bb/Gruntfile.js#L132


```diff

-          "js/jquery.easing.1.3.js",
+          "js/jquery.easing.1.4.js",
```

**Comment by tomscholz** [comment]
@kmmbvnr I created a full changelog [here](https://gist.github.com/tomscholz/0f91531243802f60a9917a60ad3f5e28)

**Comment by angrykoala** [comment]
This is happening to me with materialize-css@0.100.0 and 0.99.0 (it wasn't happening before)

Adding jqueryUI `<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>` seems to fix the problem, however I don't understand why or if there is a better fix.

I'm using materialize as part of an electron app, and I prefer to use only npm based packages
