### ISSUE TITLE
0.97.8 causes Uncaught TypeError: Materialize.updateTextFields is not a function

### ISSUE THREAD

**Issue by K1N5L4Y3R** [Dogfalo/materialize#3914]
### Description
Since I updated to 0.97.8, I was getting the following Javascript error on the console:
`Uncaught TypeError: Materialize.updateTextFields is not a function`

### Repro Steps
Prefill text inputs (as per the [documentation](http://materializecss.com/forms.html))
```
$(document).ready(function() {
  Materialize.updateTextFields();
});
```

### Workaround
I downgraded to 0.97.7 and the error does not show anymore.

### Notes
I am using [materialize-sass](https://github.com/mkhairi/materialize-sass) on a Rails project, so if this is a materialize-sass specific issue, please let me know and I can create another issue in that repository. Sorry but I'm short of time to test it with the standalone Javascript of this repository.

**Comment by kmmbvnr** [comment]
I can't reproduce http://codepen.io/kmmbvnr/pen/MbbWrL

**Comment by K1N5L4Y3R** [comment]
@kmmbvnr Thank you for checking, in that case I will figure out if the error was specific to materialize-sass (or something else). Closing this.
