### ISSUE TITLE
$(...).tapTarget is not a function

### ISSUE THREAD

**Issue by rushil16** [Dogfalo/materialize#4691]
I get error when I click for open feature discovery 
here is the reference link http://materializecss.com/feature-discovery.html
![screenshot_3](https://cloud.githubusercontent.com/assets/24586572/26104426/7028b9e8-3a5b-11e7-9357-7d17c9c83297.png)

**Comment by DanielRuf** [comment]
Please make sure you include jQuery before Materialize and not (again) after this and call the method on documentready when all scripts have loaded.

Can you provide a codepen?

**Comment by Native-Coder** [comment]
Are you using version 0.98.2? I'm using version 0.98.0, which doesn't have this feature.

**Comment by rushil16** [comment]
https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js

**Comment by DanielRuf** [comment]
Well, 0.97.8 is an old version and this was added / fixed in a newer version. The docs are always for the latest release.

**Comment by DanielRuf** [comment]
Please try if it works with 0.98.2.

**Comment by rushil16** [comment]
Okay Thank you so much for help

**Comment by rushil16** [comment]
Okay Thank you so much for help

**Comment by briancaldas93** [comment]
In the latest version it also gives problems

![image](https://user-images.githubusercontent.com/16884130/58995992-08a2d000-87bc-11e9-853a-ae4eb3f4ad86.png)


![image](https://user-images.githubusercontent.com/16884130/58996007-1b1d0980-87bc-11e9-8f12-76808c47a93e.png)

This error in console in the line:

![image](https://user-images.githubusercontent.com/16884130/58996021-2a9c5280-87bc-11e9-95d5-19f49a6da7af.png)

**Comment by DanielRuf** [comment]
Hi @briancaldass,

Which version do you use? Does an element with the class `tap-target` exist?

**Comment by JadenSWang** [comment]
Hi I have this problem and I'm using materialize version 1.0.0 and jquery 3.4.1, materialize is loaded before jquery which is loaded before the $('.tap-target').tapTarget('open') is run

**Comment by DanielRuf** [comment]
Thois is not the right order. Please put the scripts right befire the closing `</body>` tag and load jQuery before materialize.

**Comment by DanielRuf** [comment]
Also please open a new issue with all relevant details and do not comment on already closed issues.

**Comment by lukman-bahar-ap** [comment]
i have same problem, i fix this with include jquery on end of list import

import M from 'materialize-css/dist/js/materialize.min.js'
import * as $ from 'jquery';

**Comment by DanielRuf** [comment]
> import M from 'materialize-css/dist/js/materialize.min.js'
> import * as $ from 'jquery';

Depending on your version you may need jQuery. Materialize 1.0.0 does not require jQuery anymore and uses cash internally.
