### ISSUE TITLE
$("modal").openModal is not a function

### ISSUE THREAD

**Issue by alerd** [Dogfalo/materialize#3845]
I get $("modal").openModal is not a function after your release 0.97.8
openModal, open and modal properties are undefined.

It works OK in 0.97.7

**Comment by tomscholz** [comment]
@alerd Can you give a codepen please with the exact problem?

**Comment by ProProPro1** [comment]
It's changed. Read the documentation for the modal again and try this: '$('.modal').modal('open');'

**Comment by tomscholz** [comment]
@alerd I think I know what your problem is. Just change this:
$(document).ready(function() {
$('.modal-trigger').leanModal();
 });
into this:
$(document).ready(function() {
$('.modal').modal();
 });

**Comment by sch00lb0y** [comment]
@tomscholz even i tried 
`$('.modal').modal();`
modal is not working at all

**Comment by jcarioti** [comment]
Shouldn't these types of breaking changes be reserved for minor version updates as opposed to patch updates?

**Comment by acburst** [comment]
The modal plugin has been rewritten. You can read about it at the [modals page](http://materializecss.com/modals.html)

**Comment by jcarioti** [comment]
@acburst Can you address the issue that these are breaking changes included in a patch release?

**Comment by goyney** [comment]
Why would a patch release make such a breaking change? This should have been a minor version bump.

**Comment by ProProPro1** [comment]
lol

**Comment by spflow** [comment]
totally agree with the breaking change in a patch release issue; plus weak documentation. I missed this issue because it was closed, so opened one for the same problem(solution included):
https://github.com/Dogfalo/materialize/issues/3850

**Comment by jon-heller** [comment]
Also, unless I'm doing something wrong, `$('#acme').modal('open')` does not have the same behavior as `$('#acme').openModal()` had. The former animates the modal opening but doesn't apply opacity and doesn't catch closing the modal when clicking outside of it.

**Comment by spflow** [comment]
hmm, I think .modal('open') is working the same as .openModal() was, for me.

**Comment by jackric** [comment]
Please don't make breaking changes in patch releases like this

**Comment by jpduckwo** [comment]
Doh this stuffed us up too!

**Comment by alejogoez** [comment]
Materialize was be updated, also you have update the new version of the official page and ready

**Comment by aswinramakrish** [comment]
```
$.fn.openModal = function () {
    this.modal();
    this.modal('open');
};
```

```
$.fn.closeModal = function () {
    this.modal('close');
};
```

You're welcome

**Comment by Juul** [comment]
If anyone is having the same problem as @jon-heller the issue is shows up if you have an older materialize.css and a newer materialize.js so just update your .css to match the version of your .js

**Comment by urumican** [comment]
Is 0.97.6 also affected?

**Comment by RobsonFeitosa** [comment]
Para arquivo externo funcionou comigo dessa forma, como no comentario do zanozik nesse artigo.
https://github.com/Dogfalo/materialize/issues/3850

    $(#btn).on('click', function(){ 
        $(#modal1).modal();  //chama a função
        $(#modal1).modal('open'); //atribui uma ação open/close... 
    }); 
 
No mesmo arquivo index.php .. etc.. esse link funciona bem https://codepen.io/anon/pen/ZBzYwB

**Comment by master355** [comment]
The error persist , I'm using Materialize v3.1.

`
$(document).ready(function(){
... some code
});

function OpenModal() { // click a button
      $('#IdModal').modal('open'); // Error
}
`
You must use the function **openModal()** to make works. 

`
$(document).ready(function(){
... some code
});

function OpenModal() { // click a button
      $('#IdModal').openModal(); // Error
}
`

**Comment by hiteshsahu** [comment]
Update your java script files of JQuery and MaterializeCSS to latest lib from http://materializecss.com/getting-started.html
```

 <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
 <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script></script>
```

Codepen example:

https://codepen.io/hiteshsahu/pen/dVqVbW?editors=1010
